inherit_from: .rubocop_todo.yml
Style/HashSyntax:
  EnforcedStyle: ruby19
Metrics/MethodLength:
  Exclude:
    - test/**/*
Metrics/AbcSize:
  Exclude:
    - test/**/*
Layout/IndentHeredoc:
  Exclude:
    - test/**/*

